consultancy_portal/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

app_name="consultancy_portal"
urlpatterns = [
	path('',views.stats,name='stats'),
    path('stats/',views.stats,name='stats'),
	path('tweets/',views.tweets,name='tweets'),
    path('stats/<str:country_name>',views.spec_stats,name='spec_stats'),    
    path('chat_index/',views.chat_index,name='chat_index'),
    path('chatBot/',views.chatBot,name='chatBot'),
]

covid_portal/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('consultancy_portal.urls',namespace='consultancy_portal')),
    path('users/',include('users.urls',namespace="users")), 
]

users/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import authenticate, login, logout
from . import views

app_name="user"
urlpatterns = [
    #the  urls are for visitor 
	path('register/',views.register, name='register'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
    #the below urls are for consultant 
	path('consultant_Register/',views.consultant_Register,name='consultant_Register'),
	path('consultant_login/',views.consultant_login,name='consultant_login'),
	path('consultancy_index/',views.consultancy_index,name='consultancy_index'),
]

consultancy_portal/models.py
from django.db import models




		

consultancy_portal/views.py
from django.shortcuts import render
from django.http import JsonResponse ,HttpResponseRedirect
from django.urls import reverse
import requests
import random
import json
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout
import tweepy
import  os
from dotenv import load_dotenv
load_dotenv()

#Home page for covid portal app
def index(request):
	return render(request,'consultancy_portal/index.html')

def chat_index(request):
	return render(request,'consultancy_portal/chat_index.html')

# stats() shows the statistics of selected country  
def stats(request):
	# Reference : https://documenter.getpostman.com/view/11144369/Szf6Z9B3?version=latest
	data=requests.get('https://corona.lmao.ninja/v2/countries?yesterday&sort').json()
	country_name=request.GET.get('search') #the GET request gets reponse from the user of specific country eg: india
	if country_name:
		return HttpResponseRedirect(reverse('consultancy_portal:spec_stats',args=[country_name]))						
	return render(request,'consultancy_portal/stats.html',{'data':data})

def spec_stats(request,country_name):
	# Reference : https://documenter.getpostman.com/view/11144369/Szf6Z9B3?version=latest
	# statistics of specific country is retrived eg: statistics of india .
	data=requests.get(f'https://corona.lmao.ninja/v2/countries/{country_name}').json()
	return render(request,'consultancy_portal/spec_stats.html',{'data':data})

def tweets(request):
	auth = tweepy.OAuthHandler(os.getenv('consumer_key'),os.getenv('consumer_secret'),os.getenv('access_token'),os.getenv('access_token_secret'))
	api = tweepy.API(auth)
#	search_words = ["#covid19", "#omicron"]
#	date_since = "2020-05-21"
	tweets = tweepy.Cursor(api.search_tweets ,q=["#covid19", "#omicron"],lang="en",since_id="2020-05-21").items(50)
	tweets_copy = []
	for tweet in tweets:
		tweets_copy.append(tweet.text)
	return render(request,'consultancy_portal/tweets.html',{'tweets_copy':tweets_copy})

	
def chatBot(request):
	query = str(request.GET.get("query"))
	lemmatizer=WordNetLemmatizer()

	with open('jsonfile.json') as fileobj:
		readobj=json.load(fileobj)

	words=[]
	classes=[]
	documents=[]
	stop_words=['is','and','the','a','are','i','it']
	cleaned_word=[]

	for intent in readobj['intents']:
		for pattern in intent['patterns']:
			word_list=word_tokenize(pattern)
			words.extend(word_list)
			documents.append((word_list,intent['tag']))
			if intent['tag'] not in classes:
				classes.append(intent['tag'])

	# vectorizer = TfidfVectorizer()
	# X = vectorizer.fit_transform(cleaned_word)

	words = sorted(set(words))
	classes = sorted(set(classes))

	def clean_corpus(words):
		words = [doc.lower() for doc in words]
		for w in words:
			if w not in stop_words and w.isalpha():
				w=lemmatizer.lemmatize(w)
				cleaned_word.append(w)
		return(cleaned_word)
	
	cleaned_list = clean_corpus(words)

	words = sorted(set(words))
	classes = sorted(set(classes))
	# y = encoder.fit_transfrom(np.array(classes), reshape(-1, 1))

	training =[]
	output_empty = [0] * len(classes)


	for document in documents:
		bag =[]
		word_patterns = document[0]

		word_patterns = [lemmatizer.lemmatize(word.lower()) for word in word_patterns]

		for word in words :
			bag.append(1) if word in word_patterns else bag.append(0)
		output_row = list(output_empty)
		output_row[classes.index(document[1])] = 1 
		training.append([bag,output_row])

	'''Neural Network'''
	random.shuffle(training)
	training = np.array(training,dtype=object)
	train_x = list(training[:,0])
	train_y = list(training[:,1])

	model = Sequential([Dense(128, input_shape = (len(train_x[0]),),activation='relu'),Dropout(0.2),Dense(64, activation='relu'),Dropout(0.2),Dense(len(train_y[0]),activation = 'softmax')])
	sgd = tensorflow.keras.optimizers.SGD(learning_rate=0.01, decay = 1e-6, momentum = 0.9, nesterov = True)
	model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
	history = model.fit(np.array(train_x),np.array(train_y),epochs=20,batch_size=1,verbose=7)
	# model.save('chatbot_model.model',history)


	def cleaning_up_message(message):
		message_word = word_tokenize(message)
		message_word = [lemmatizer.lemmatize(word.casefold()) for word in message_word]
		return message_word


	def bag_of_words(message):
		message_word = cleaning_up_message(message)
		bag = [0]*len(words)
		for w in message_word:
			for i, word in enumerate(words):
				if word == w:
					bag[i] = 1
		return np.array(bag)
		
	INTENT_NOT_FOUND_THRESHOLD = 0.25

	def predict_intent_tag(message):
		BOW = bag_of_words(message)
		res = model.predict(np.array([BOW]))[0]
		results = [[i,r] for i,r in enumerate(res) if r > INTENT_NOT_FOUND_THRESHOLD ]
		results.sort(key = lambda x : x[1] , reverse = True)
		return_list = []
		for r in results:
			return_list.append({ 'intent': classes[r[0]], 'probability': str(r[1]) })
		return return_list

	def get_response(intents_list , intents_json):
		tag = intents_list[0]['intent']
		list_of_intents = intents_json['intents']
		for i in list_of_intents:
			if i['tag'] == tag :
				result= random.choice (i['responses'])
				break
			# elif i['tag']!=tag:
			#     result=random.choice(["Invalid response","Sorry:), I didn't get what you are saying","Pardon me..!"])
			#     break
		return result

	print(" Aapi is Running ! ")
	message = query
	ints = predict_intent_tag(message)
	bot_response = get_response(ints, readobj)
	# print(bot_response)
	print(bot_response)
	return JsonResponse({"Bot": bot_response})
	

    
    

	

	

consultancy_portal/templates/consultancy_portal/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <!-- Bootstrap CSS 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
  <body>
  <a href="{% url 'consultancy_portal:stats' %}">Statistics</a>
  <a href="{% url 'consultancy_portal:tweets' %}">Tweets</a>
  {% if user.is_authenticated %}
 <a>Hello, {{ user.username }}.</a>
 <a href="{% url 'users:logout' %}">log out</a>
 {% else %}
 <a href="{% url 'users:register' %}">register</a>
 <a href="{% url 'users:login' %}">log in</a>
 <a href="{% url 'consultancy_portal:chat_index' %}">chat</a>
 {% endif %}
  {% block content %}{% endblock content %}      
  </body>
</html>

consultancy_portal/templates/consultancy_portal/consultancy_index.html
{% extends "consultancy_portal/base.html"%}
{% block header %}
    <title>Hello, world!</title>
{% endblock header%}
{% block content %}
  <body>
    <h1>Hello, world!{{user.username}} </h1>
  </body>
{% endblock content %}
  

consultancy_portal/templates/consultancy_portal/spec_stats.html
{% extends "consultancy_portal/base.html" %}
{% block header %}
    <title>Hello, world!</title>
{% endblock header %}
{% block content %}
    <h1>Hello, world!</h1>
    
   <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Country</th>
      <th scope="col">Active</th>
      <th scope="col">Cases</th>
      <th scope="col">Recovered</th>
      <th scope="col">Death</th>
    </tr>
  </thead>
  <tbody>
    <tr>    
      <td>{{data.country}}</td>    
      <td>{{data.active}}</td>
      <td>{{data.cases}}</td>    
      <td>{{data.recovered}}</td> 
      <td>{{data.deaths}}</td>
    </tr>
  </tbody>
</table>
{% endblock content %}

consultancy_portal/templates/consultancy_portal/stats.html
{% extends "consultancy_portal/base.html" %}
{% block header %}
    <title>Covid portal  </title>
{% endblock header %}
{% block content %}
    <h1>Covid portal</h1>
    
  <form class="form-inline my-2 my-lg-0" method='get' action="{% url 'consultancy_portal:stats' %}" >
   <input class="form-control mr-sm-2" type="search" name="search">
  <button class="btn btn btn-outline-info my-2 my-sm-0" type="submit"> Search </button>
  </form>
     
   <table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">Country</th>
      <th scope="col">Active</th>
      <th scope="col">Cases</th>
      <th scope="col">Recovered</th>
      <th scope="col">Death</th>
    </tr>
  </thead>
  <tbody>
  {% for d in data%}
    <tr>    
      <td>{{d.country}}</td>    
      <td>{{d.active}}</td>
      <td>{{d.cases}}</td>    
      <td>{{d.recovered}}</td> 
      <td>{{d.deaths}}</td>
    </tr>
     {%endfor%} 
  </tbody>
</table>
{% endblock content %}

consultancy_portal/templates/consultancy_portal/tweets.html
{% extends 'consultancy_portal/base.html' %}
{% block content %}
  <body>
     <table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">Tweets</th>
    </tr>
  </thead>
  <tbody>
  {% for tweet in tweets_copy%}
    <tr>    
      <td>{{tweet}}<br><br></td>
    </tr>
     {%endfor%} 
  </tbody>
</table>
  </body>
{% endblock content %}