covid_portal/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('consultancy_portal.urls',namespace='consultancy_portal')),
    path('users/',include('users.urls',namespace="users")), 
]

users/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import authenticate, login, logout
from . import views

app_name="user"
urlpatterns = [
    #the  urls are for visitor 
	path('register/',views.register, name='register'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
    #the below urls are for consultant 
	path('consultant_Register/',views.consultant_Register,name='consultant_Register'),
	path('consultant_login/',views.consultant_login,name='consultant_login'),
	path('consultancy_index/',views.consultancy_index,name='consultancy_index'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
	
class ConsultantForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()
    Designation=forms.CharField(max_length=101)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm , UserCreationForm
from django.contrib.auth import authenticate, login , logout
from consultancy_portal.views import index  
from users.forms import UserRegistrationForm , ConsultantForm

#  register() is for visitor to register into the site 
def register(request):
	if request.method =='POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('consultancy_portal:index')
	else:
		form = UserRegistrationForm()
	return render(request, 'users/register.html',  {'form': form})
    
#  login_view() is for visitor to log in  the site
def login_view(request):
	if request.method=='POST':
		form=AuthenticationForm(request,data=request.POST)
		username=request.POST.get('username')
		password = request.POST.get('password') 
		user=authenticate(request,username=username, password=password)
		if form.is_valid():
			login(request,user)
			return redirect('consultancy_portal:index')
	else:
		form=AuthenticationForm()
	return render(request, 'users/login.html', {'form':form})

#  consultant_Register() is for consultant to register into the site
def consultant_Register(request):
	if request.method=='POST':
		form=ConsultantForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('users:consultant_login')
	else:
		form=ConsultantForm()
	return render(request,'users/consultant_Register.html',{'form':form})

#  consultant_login() is for consultant to log in  the site
def consultant_login(request):
	if request.method=='POST':
		form=AuthenticationForm(request,data=request.POST)
		username=request.POST.get('username')
		password = request.POST.get('password')
		designation=request.POST.get('designation')
		user=authenticate(request,username=username, password=password)
		if form.is_valid():
			login(request,user)
			return redirect('users:consultancy_index')
	else:
		form=AuthenticationForm()
	return render(request, 'users/consultant_login.html', {'form':form})

#consultancy_index provides a different home page to the consultant 
def consultancy_index(request):
    return redirect('consultancy_portal:index')
	
def logout_view(request):
	logout(request)
	return render(request, 'consultancy_portal/index.html')
	

users/templates/users/consultant_Register.html
{% extends "consultancy_portal/base.html" %}
{% block content %}
 <form method="post" action="{% url 'users:consultant_Register' %}" class ="form">
 {% csrf_token %}
 {{ form.as_p }}
  <button name="submit" class="btn btn-primary">Register as consultant</button>
 <input type="hidden" name="next" />
 </form>
{% endblock content %}

users/templates/users/consultant_login.html
{% extends "consultancy_portal/base.html" %}
{% block header %}
 <h2>Log in to your account.</h2>
{% endblock header %}
{% if form.errors %}
 <p>Your username and password didn't match. Please try again.</p>
 {% endif %}
{% block content %}
<form method="post" action="{% url 'users:consultant_login' %}" class="form">
 {% csrf_token %}
 {{form.as_p }}
 <button name="submit" class="btn btn-primary">log in</button>
<input type="hidden" name="next" value="{% url 'users:consultancy_index' %}" />
 </form> 
 <p>Don't have an account? <a href="{% url 'users:register' %}">Signup here</a></p>
 {% endblock content %}

users/templates/users/login.html
{% extends "consultancy_portal/base.html" %}
{% block header %}
 <h2>Log in to your account.</h2>
{% endblock header %}
{% if form.errors %}
 <p>Your username and password didn't match. Please try again.</p>
 {% endif %}
{% block content %}
<form method="post" action="{% url 'users:login' %}" class="form">
 {% csrf_token %}
 {{form.as_p }}
 <button name="submit" class="btn btn-primary">log in</button>
<input type="hidden" name="next" value="{% url 'consultancy_portal:index' %}" />
 </form> 
 <p>Don't have an account? <a href="{% url 'users:register' %}">Signup here</a></p>
 {% endblock content %}

users/templates/users/logout.html
{% extends "consultancy_portal/base.html" %}
{%block content %}
<h3>logout</h3>
<h3>Successfully logged Out</h3>
{% endblock content %}

users/templates/users/register.html
{% extends "consultancy_portal/base.html" %}
{% block content %}
 <form method="post" action="{% url 'users:register' %}" class ="form">
 {% csrf_token %}
 {{ form.as_p }}
  <button name="submit" class="btn btn-primary">Resigter</button>
 <input type="hidden" name="next" />
 </form>
  <p> Login as a ?<a href="{% url 'users:consultant_login'%}">consultant </a>
 <p> Register as a ?<a href="{% url 'users:consultant_Register'%}">consultant </a>
{% endblock content %}